### ISSUE TITLE
Undo button does not correctly restore last saved state

### ISSUE THREAD

**Issue by empicano** [fastsurvey/console#129]
https://user-images.githubusercontent.com/26978146/137817773-8c432099-f70b-4d20-9b86-80bbd709b326.mov

**Comment by dostuffthatmatters** [comment]
There are two configs in editor mode `centralConfig` (in sync with database) and `localConfig` (the one currently visible). So when changing stuff in the editor, only the `localConfig` should be modified and only overwrite the `centralConfig` when clicking on save.

I think the error is the following: The very first change to the `localConfig`, is also applied to the centralConfig, because I did not deepcopy it correctly but modified it by reference.

The following code deepcopies all the top level attributes of an object. That's why this bug is only happening on fields, not on the general stuff. But the fields are only copied by reference.
```js
const newConfig = {
    ...localConfig,
};
```

A simple deepcopy can be done by simple converting it to string and back:
```js
const newConfig = JSON.parse(JSON.stringify(localConfig));
```

**Comment by empicano** [comment]
Nice! Unintentionally modifying objects always gives really weird bugs 😄

Some loose thoughts (feel free to ignore 😄):

Maybe it could be cool to even save a snapshot of the configuration every 10 seconds or so (if it changed), to have a full snapshot history that we can cycle through via `CTRL-Z` / `CTRL-Y`. With the configuration not taking that much space, you would probably still get away fine with snapshots without optimizations like saving only the changes.

Although then you'd probably need to differentiate between the two actions, like naming the one to go back to `centralConfig` "revert" or something.

**Comment by dostuffthatmatters** [comment]
> Maybe it could be cool to even save a snapshot of the configuration every 10 seconds or so (if it changed), to have a full snapshot history that we can cycle through via `CTRL-Z` / `CTRL-Y`. With the configuration not taking that much space, you would probably still get away fine with snapshots without optimizations like saving only the changes.

I was thinking about having a document history some day - we should ask users about this first. Basically every save will result in a new version. To reduce db load, this could be done via cookies, there we can store up to 5MB, so a lot of configs. Would be nice though to have this in the database, but I don't want to blow up the db size without many people making use of this.
